### ISSUE TITLE
Train Acc always 50%

### ISSUE THREAD

**Issue by ZzzhHe** [brijeshiitg/GNCNN-Deep_learning_for_steganalysis_via_convolutional_neural_networks#1]
Dear author
I'm using the BOSSbase_1.01 dataset,HUGO algorithm 0.4bpp
and 8000 train set, 2000 val set, epoch = 50
but always get train_acc = 50% and train_loss = 69%
I think the model never get trained.
I don't know why, maybe my train function or preprocessing is not good
could you upload your train code to this repo? i want to find my fault
thanks a lot :)

**Comment by Floating-dust** [comment]
I met the same problem. Have you solved it？

**Comment by 876arham** [comment]
Can you share your preprocessing code , or how did you use HPF @Floating-dust

**Comment by Floating-dust** [comment]
> Can you share your preprocessing code , or how did you use HPF @Floating-dust

Actually, I used HPF by reference to the implementation of XuNet. You can get the code from [https://github.com/brijeshiitg/XuNet-Structural-Design-of-Convolutional-Neural-Networksfor-Steganalysis/blob/master/Xunet.py](url). @876arham

**Comment by 876arham** [comment]
> > Can you share your preprocessing code , or how did you use HPF @Floating-dust
> 
> Actually, I used HPF by reference to the implementation of XuNet. You can get the code from [https://github.com/brijeshiitg/XuNet-Structural-Design-of-Convolutional-Neural-Networksfor-Steganalysis/blob/master/Xunet.py](url). @876arham

I am actually stuck at how to pass it through the HPF in keras, if possible can you share your pytorch preprocessing code or tensorflow? @F
Floating-dust

**Comment by Floating-dust** [comment]
> > > Can you share your preprocessing code , or how did you use HPF @Floating-dust
> > 
> > 
> > Actually, I used HPF by reference to the implementation of XuNet. You can get the code from [https://github.com/brijeshiitg/XuNet-Structural-Design-of-Convolutional-Neural-Networksfor-Steganalysis/blob/master/Xunet.py](url). @876arham
> 
> I am actually stuck at how to pass it through the HPF in keras, if possible can you share your pytorch preprocessing code or tensorflow? @f
> Floating-dust

I've just copied the implementation in the link above and I'm sorry if that doesn't help you. @876arham

**Comment by brijeshiitg** [comment]
Training code is now available.
